<?php
namespace app\controllers;
/**
 * Created by PhpStorm.
 * User: User
 * Date: 26.01.2019
 * Time: 5:08
 */
class Controller extends \yii\web\Controller
{
    public $categories;

    public function beforeAction($action)
    {
        $this->categories = \app\models\Categories::find()->all();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}